version: '3.3'

#https://www.digitalocean.com/community/tutorials/how-to-set-up-flask-with-mongodb-and-docker
services:
    wallet-profile-mongodb-server:
        env_file:
          - ./src/config/mainnet/db_secrets.env
          - ./src/config/mainnet/app_secrets.env
        volumes:
          - ./data/mongo:/data/db
        ports:
          - 27017:27017

    wallet-profile-app-server:
        env_file:
          - ./src/config/mainnet/db_secrets.env
          - ./src/config/mainnet/app_secrets.env
        ports:
            - 8080:8080
        expose:
            - 8080
        volumes:
            - ./src:/pythonapp/src:ro