version: '3.3'

#https://www.digitalocean.com/community/tutorials/how-to-set-up-flask-with-mongodb-and-docker
services:
    wallet-profile-mongodb-server:

        build:
            context: DockerFiles/mongo
            dockerfile: DockerFile
        image: wallet-profile-mongodb-server
        container_name: wallet-profile-mongodb-server
        command: mongod --auth --quiet
        logging:
            driver: "none"
        restart: on-failure
    wallet-profile-app-server:
        build:
            context: .
            dockerfile: DockerFiles/app/DockerFile
        image: wallet-profile-app-server
        container_name: wallet-profile-app-server

        depends_on:
            - wallet-profile-mongodb-server


volumes:
    data:
        driver: local