version: '3.3'

#https://www.digitalocean.com/community/tutorials/how-to-set-up-flask-with-mongodb-and-docker
services:
    wallet-profile-mongodb-server:
        env_file:
          - ./src/config/mainnet/db_secrets.env
          - ./src/config/mainnet/app_secrets.env
        volumes:
          - ./data/mongo:/data/db
        network_mode: "host"


    wallet-profile-app-server:
        env_file:
          - ./src/config/mainnet/db_secrets.env
          - ./src/config/mainnet/app_secrets.env
        network_mode: "host"
        volumes:
            - ./src:/pythonapp/src:ro