
FROM mongo:6.0.2-focal

COPY init-mongo.sh /docker-entrypoint-initdb.d/mongo-init.sh
RUN ["chmod", "+x", "/docker-entrypoint-initdb.d/mongo-init.sh"]

CMD [ "/docker-entrypoint-initdb.d/mongo-init.sh" ]
